/*
 * Copyright (C) 2022 Anonymous Idiot
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

// This list is pulled from wiz.exe itself, not from the data files

static const QString item_stis[] =
{
    /* 00: */ "Dagger.sti",
    /* 01: */ "LongSword.sti",
    /* 02: */ "Bipennis.sti",
    /* 03: */ "BattleAxe.sti",
    /* 04: */ "Flail.sti",
    /* 05: */ "Mace.sti",
    /* 06: */ "Hammer.sti",
    /* 07: */ "ShortStaff.sti",
    /* 08: */ "Halberd.sti",
    /* 09: */ "Spear.sti",
    /* 0a: */ "BoStaff.sti",
    /* 0b: */ "LongBow.sti",
    /* 0c: */ "Crossbow.sti",
    /* 0d: */ "Sling.sti",
    /* 0e: */ "GreatSword.sti",
    /* 0f: */ "Rapier.sti",
    /* 10: */ "Katana.sti",
    /* 11: */ "LongStaff.sti",
    /* 12: */ "Wand.sti",
    /* 13: */ "MagicStave.sti",
    /* 14: */ "QuestionMark.sti",
    /* 15: */ "Shuriken.sti",
    /* 16: */ "Arrow.sti",
    /* 17: */ "SlingShot.sti",
    /* 18: */ "KiteShield.sti",
    /* 19: */ "Basnet.sti",
    /* 1a: */ "PlateTorso.sti",
    /* 1b: */ "PlateLegs.sti",
    /* 1c: */ "GauntletSteel.sti",
    /* 1d: */ "Sollerets.sti",
    /* 1e: */ "Amulet.sti",
    /* 1f: */ "Ring.sti",
    /* 20: */ "BluePotion.sti",
    /* 21: */ "Scroll.sti",
    /* 22: */ "PowderPouch.sti",
    /* 23: */ "Key.sti",
    /* 24: */ "Locket.sti",
    /* 25: */ "GreatBow.sti",
    /* 26: */ "RoundShield.sti",
    /* 27: */ "WizardCone.sti",
    /* 28: */ "LeatherHelm.sti",
    /* 29: */ "Cuirass.sti",
    /* 2a: */ "LeatherHauberk.sti",
    /* 2b: */ "Greaves.sti",
    /* 2c: */ "LeatherPants.sti",
    /* 2d: */ "Gloves.sti",
    /* 2e: */ "Sandals.sti",
    /* 2f: */ "Buskins.sti",
    /* 30: */ "Boots.sti",
    /* 31: */ "Book.sti",
    /* 32: */ "Ankh.sti",
    /* 33: */ "Ninjato.sti",
    /* 34: */ "WarHammer.sti",
    /* 35: */ "Flamberge.sti",
    /* 36: */ "Bullwhip.sti",
    /* 37: */ "Sai.sti",
    /* 38: */ "Nunchuka.sti",
    /* 39: */ "Glaive.sti",
    /* 3a: */ "BlackSword.sti",
    /* 3b: */ "FireSword.sti",
    /* 3c: */ "RobeUpper.sti",
    /* 3d: */ "RobeLower.sti",
    /* 3e: */ "HalterTop.sti",
    /* 3f: */ "Skirt.sti",
    /* 40: */ "SkullCap.sti",
    /* 41: */ "FeatheredCap.sti",
    /* 42: */ "Mitre.sti",
    /* 43: */ "QuestionMark.sti",
    /* 44: */ "Kabuto.sti",
    /* 45: */ "Do-MaruUpper.sti",
    /* 46: */ "Tosei-GusokuLower.sti",
    /* 47: */ "Burgonet.sti",
    /* 48: */ "FurLegs.sti",
    /* 49: */ "Cloak.sti",
    /* 4a: */ "QuestionMark.sti",
    /* 4b: */ "QuestionMark.sti",
    /* 4c: */ "Garland.sti",
    /* 4d: */ "CatONineTails.sti",
    /* 4e: */ "SilverCross.sti",
    /* 4f: */ "QuestionMark.sti",
    /* 50: */ "QuestionMark.sti",
    /* 51: */ "Bracelet.sti",
    /* 52: */ "Necklace.sti",
    /* 53: */ "Quarrel.sti",
    /* 54: */ "QuestionMark.sti",
    /* 55: */ "Coif.sti",
    /* 56: */ "Hauberk.sti",
    /* 57: */ "ChainLower.sti",
    /* 58: */ "MailMittens.sti",
    /* 59: */ "ChainHosen.sti",
    /* 5a: */ "Lance.sti",
    /* 5b: */ "Armet.sti",
    /* 5c: */ "NinjaCowl.sti",
    /* 5d: */ "NinjaGarbUpper.sti",
    /* 5e: */ "NinjaGarbLower.sti",
    /* 5f: */ "TabiBoots.sti",
    /* 60: */ "Heaume.sti",
    /* 61: */ "BoxHelm.sti",
    /* 62: */ "DiamondRing.sti",
    /* 63: */ "Bag.sti",
    /* 64: */ "RedPotion.sti",
    /* 65: */ "GreenPotion.sti",
    /* 66: */ "PurplePotion.sti",
    /* 67: */ "YellowPotion.sti",
    /* 68: */ "QuestionMark.sti",
    /* 69: */ "T'RangStaff.sti",
    /* 6a: */ "GauntletBronze.sti",
    /* 6b: */ "QuestionMark.sti",
    /* 6c: */ "LightSword.sti",
    /* 6d: */ "QuestionMark.sti",
    /* 6e: */ "QuestionMark.sti",
    /* 6f: */ "QuestionMark.sti",
    /* 70: */ "Dart.sti",
    /* 71: */ "PowderShot.sti",
    /* 72: */ "Musket.sti",
    /* 73: */ "QuestionMark.sti",
    /* 74: */ "Stone.sti",
    /* 75: */ "Stick.sti",
    /* 76: */ "ShortSword.sti",
    /* 77: */ "QuestionMark.sti",
    /* 78: */ "Bagpipes.sti",
    /* 79: */ "Lyre.sti",
    /* 7a: */ "Lute.sti",
    /* 7b: */ "Horn.sti",
    /* 7c: */ "QuestionMark.sti",
    /* 7d: */ "Bracelet2.sti",
    /* 7e: */ "Shuriken2.sti",
    /* 7f: */ "QuestionMark.sti",
    /* 80: */ "Wand2.sti",
    /* 81: */ "YellowPotion2.sti",
    /* 82: */ "MediumShield.sti",
    /* 83: */ "Omnigun_1.sti",
    /* 84: */ "QuestionMark.sti",
    /* 85: */ "QuestionMark.sti",
    /* 86: */ "QuestionMark.sti",
    /* 87: */ "QuestionMark.sti",
    /* 88: */ "Saxaphone.sti",
    /* 89: */ "Violin.sti",
    /* 8a: */ "Drum.sti",
    /* 8b: */ "Bullroar.sti",
    /* 8c: */ "QuestionMark.sti",
    /* 8d: */ "emptybottle.sti",
    /* 8e: */ "Stix.sti",
    /* 8f: */ "rocket.sti",
    /* 90: */ "rocketlauncher.sti"
};
